<?php include 'header.php'?>
<!-- Close Navbar -->
<!-- Slide -->

<div class="row" style="padding:0; margin: 0;">
    <div class="swiper-container col-xs-12" id="swiper-header">
        <div class="swiper-wrapper">

            <div class="swiper-slide">
                <img class="col-xs-12 img-responsive" src="Assets/img/HIJAB.png" alt="First slide">
            </div>
            <div class="swiper-slide">
                <img class="col-xs-12 img-responsive" src="Assets/img/HIJAB.png" alt="Second slide">
            </div>
            <div class="swiper-slide">
                <img class="col-xs-12 img-responsive" src="Assets/img/HIJAB.png" alt="Third slide">
            </div>
        </div>
        <div class="swiper-pagination">
        </div>
    </div>
</div>


<div class="container-fluid">
    <i class="fa fa-chevron-circle-left fa-4x kiri" id="slide"></i>
    <i class="fa fa-chevron-circle-right fa-4x kanan" id="slider"> </i>
</div>
<!-- close hijab -->


<!-- Your Style -->

<div class="container-fluid ">

    <!-- text -->
    <div class="container m-t-40 text-center">
        <p style="font-family: 'Nunito Sans', sans-serif;font-size: 40px;"> YOUR STYLE IN HERE </p>
        <p style="font-family: 'Nunito Sans', sans-serif; font-size: 17px;"> Nikmati pengalaman belanja produk baju
            muslimah terbaru dan tetap kekinian buat kamu </p>
    </div>
    <!-- close text -->

    <div class="container text-center">
        <div class="row mt-4">
            <div class="col-md-4 box-img">
                <img src="Assets/img/jilbabcoklat.png" width="100%" alt="">
            </div>
            <div class="col-md-4 box-img">
                <img src="Assets/img/update.png" width="100%" alt="">
            </div>
            <div class="col-md-4 box-img">
                <img src="Assets/img/jilbabcoklat.png" width="100%" alt="">
            </div>
        </div>

        <div class="row">
            <div class="col-md-4 box-img">
                <img src="Assets/img/popular.png" width="100%" alt="">
            </div>
            <div class="col-md-4 box-img">
                <img src="Assets/img/jilbabcoklat.png" width="100%" alt="">
            </div>
            <div class="col-md-4 box-img">
                <img src="Assets/img/real (1).png" width="100%" alt="">
            </div>
        </div>
        <!-- Close Your Style -->




        <!-- New Arival -->
        <p class="m-t-70" style="font-family: 'Nunito Sans', sans-serif; font-size: 40px">
            <span style="color :#00C09D">
                NEW </span> ARRIVAL </p>

    </div>
    <!-- Slide -->

    <div class="swiper-container col-md-12 col-xs-12 m-t-40" id="swiper-one">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="card-user bg-white col-md-8 offset-md-2 col-xs-12 shadow p-3 mb-5 rounded">
                    <div class="box-img-card col-md-12 col-xs-12">
                        <a href="#">
                            <img src="Assets/img/Jilbababu.png" alt="" class="col-md-12 col-xs-12">
                        </a>
                    </div>
                    <div class="col-md-12 col-xs-12 row ">
                        <p class="col-md-6 title-product">Kerudung Hitam Syelika </p>
                        <span class="col-md-6 text-right" style="color :#00C09D "> Rp 50.000</span>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="card-user bg-white col-md-8 offset-md-2 col-xs-12 shadow p-3 mb-5 rounded">
                    <div class="box-img-card col-md-12 col-xs-12">
                        <a href="#">
                            <img src="Assets/img/Jilbababu.png" alt="" class="col-md-12 col-xs-12">
                        </a>
                    </div>
                    <div class="col-md-12 col-xs-12 row ">
                        <p class="col-md-6 title-product">Kerudung Hitam Syelika </p>
                        <span class="col-md-6 text-right" style="color :#00C09D "> Rp 50.000</span>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="card-user bg-white col-md-8 offset-md-2 col-xs-12 shadow p-3 mb-5 rounded">
                    <div class="box-img-card col-md-12 col-xs-12">
                        <a href="#">
                            <img src="Assets/img/Jilbababu.png" alt="" class="col-md-12 col-xs-12">
                        </a>
                    </div>
                    <div class="col-md-12 col-xs-12 row ">
                        <p class="col-md-6 title-product">Kerudung Hitam Syelika </p>
                        <span class="col-md-6 text-right" style="color :#00C09D "> Rp 50.000</span>
                    </div>
                </div>
            </div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
    <!-- Close Slide -->
    <!-- Close New Arival -->



    <!-- Top Seller -->
    <div class="container text-center">
        <p class="m-t-90" style="font-family: 'Nunito Sans', sans-serif; font-size: 40px"><span style="color :#00C09D">
                TOP </span> SELLER </p>

    </div>
    <!-- Swiper -->
    <div class="swiper-container col-md-12 col-xs-12 m-t-40" id="swiper-two">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="card-user bg-white col-md-8 offset-md-2 col-xs-12 shadow p-3 mb-5 rounded">
                    <div class="box-img-card col-md-12 col-xs-12">
                        <a href="#">
                            <img src="Assets/img/Jilbababu.png" alt="" class="col-md-12 col-xs-12">
                        </a>
                    </div>
                    <div class="col-md-12 col-xs-12 row ">
                        <p class="col-md-6 title-product">Kerudung Hitam Syelika </p>
                        <span class="col-md-6 text-right" style="color :#00C09D "> Rp 50.000</span>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="card-user bg-white col-md-8 offset-md-2 col-xs-12 shadow p-3 mb-5 rounded">
                    <div class="box-img-card col-md-12 col-xs-12">
                        <a href="#">
                            <img src="Assets/img/Jilbababu.png" alt="" class="col-md-12 col-xs-12">
                        </a>
                    </div>
                    <div class="col-md-12 col-xs-12 row ">
                        <p class="col-md-6 title-product">Kerudung Hitam Syelika </p>
                        <span class="col-md-6 text-right" style="color :#00C09D "> Rp 50.000</span>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="card-user bg-white col-md-8 offset-md-2 col-xs-12 shadow p-3 mb-5 rounded">
                    <div class="box-img-card col-md-12 col-xs-12">
                        <a href="#">
                            <img src="Assets/img/Jilbababu.png" alt="" class="col-md-12 col-xs-12">
                        </a>
                    </div>
                    <div class="col-md-12 col-xs-12 row ">
                        <p class="col-md-6 title-product">Kerudung Hitam Syelika </p>
                        <span class="col-md-6 text-right" style="color :#00C09D "> Rp 50.000</span>
                    </div>
                </div>
            </div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>

    <!-- Close Top Seller -->


    <!-- Discount -->
    <div class="container text-center">
        <p class="m-t-60" style="font-family: 'Nunito Sans', sans-serif; font-size: 40px; color:#00C09D  "> DISCOUNT
        </p>

    </div>

    <div class="swiper-container col-md-12 col-xs-12 m-t-40" id="swiper-three">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="card-user bg-white col-md-8 offset-md-2 col-xs-12 shadow p-3 mb-5 rounded">
                    <div class="box-img-card col-md-12 col-xs-12">
                        <a href="#">
                            <img src="Assets/img/jilbabcoklat.png" alt="" class="col-md-12 col-xs-12">
                        </a>
                    </div>
                    <div class="col-md-12 col-xs-12 row ">
                        <p class="col-md-6 title-product">Kerudung Hitam Syelika </p>
                        <span class="col-md-6 text-right" style="color :#00C09D "> Rp 50.000</span>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="card-user bg-white col-md-8 offset-md-2 col-xs-12 shadow p-3 mb-5 rounded">
                    <div class="box-img-card col-md-12 col-xs-12">
                        <a href="#">
                            <img src="Assets/img/jilbabcoklat.png" alt="" class="col-md-12 col-xs-12">
                        </a>
                    </div>
                    <div class="col-md-12 col-xs-12 row ">
                        <p class="col-md-6 title-product">Kerudung Hitam Syelika </p>
                        <span class="col-md-6 text-right" style="color :#00C09D "> Rp 50.000</span>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="card-user bg-white col-md-8 offset-md-2 col-xs-12 shadow p-3 mb-5 rounded">
                    <div class="box-img-card col-md-12 col-xs-12">
                        <a href="#">
                            <img src="Assets/img/jilbabcoklat.png" alt="" class="col-md-12 col-xs-12">
                        </a>
                    </div>
                    <div class="col-md-12 col-xs-12 row ">
                        <p class="col-md-6 title-product">Kerudung Hitam Syelika </p>
                        <span class="col-md-6 text-right" style="color :#00C09D "> Rp 50.000</span>
                    </div>
                </div>
            </div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>

</div>
<!-- Close Discount -->

<?php include 'footer.php' ?>

<script>
    $('#beranda').addClass('nav-active');
</script>